### ISSUE TITLE
Composer file

### ISSUE THREAD

**Issue by pdias** [aweber/AWeber-API-PHP-Library#31]
Hello,

Can you create a file "composer.json" and make the api installable by composer ?

Thanks,

Paulo

**Comment by webrevllc** [comment]
Thanks @ajcerqueti still dealing with this in September...

**Comment by hellofromtonya** [comment]
Hey gang, you need to change your `composer.json` file.  Since you are not using Namespacing, you can't use the PSR4 option to autoload.  Instead autoload the files like this:

```    "autoload" : {
        "classmap": [],
        "files": [
            "aweber_api/aweber_api.php"
        ]
    },```

and then you can autoload any other files too that you need.  Or you can add a `namespace Aweber;` and then PSR4 will work for you.

Cheers.

**Comment by vladunguru** [comment]
I prefer to autoload aweber classes only when needed, so I added this code inside the autoloaded file defining my wrapper class:
```
spl_autoload_register(function(){
	require_once(realpath(__DIR__ . '/../../vendor/aweber/aweber/aweber_api/aweber.php'));
});

class AWeber { ... }
```

**Comment by vitr** [comment]
2 years now)) and there is no v2.0
