### ISSUE TITLE
Authenticating Public Apps

### ISSUE THREAD

**Issue by paultofunmi** [aweber/AWeber-API-PHP-Library#68]
Hi all, how do I authenticate users in a public app.

Here is my code: 
`$r = "https://auth.aweber.com/1.0/oauth/authorize_app/{$this->appId}";
            header("Location: $r");   `

I am redirected to the login screen 
`https://auth.aweber.com/1.0/oauth/authorize_app/########`

but the following error is shown
`404 Not Found
The resource could not be found.`

**Comment by KMChappell** [comment]
I'm not able to replicate any issues on the AWeber side. Can you send an email with the details of your request (such as your app ID and the time of the request) to api@aweber.com so we can help you figure out where the issue lies?

In the future you'll usually get a faster reply by sending an email to api@aweber.com, that inbox is monitored more frequently than the issues page here.

**Comment by paultofunmi** [comment]
Resolved now. Thanks
